### ISSUE TITLE
Feature - VPC flow log support

### ISSUE THREAD

**Issue by mime-frame** [airbnb/streamalert#16]
Feature - VPC flow log support

Likely via http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Subscriptions.html?tag=vig-20#LambdaFunctionExample

**Comment by strcrzy** [comment]
this is really 3 things

- [ ] terraform to enable flow logs and pipe to kinesis via cloudwatch subscription (#39)

- [ ] gzip-json record parser (#40)

- [ ] json nested record parser (1784238) 

the gzip and nested json work will need to be merged but after that this should be good to go!

**Comment by strcrzy** [comment]
this should now be technically supported and documented with #39 and #40. 
i will add some integration tests before closing this issue though.
