### ISSUE TITLE
Feature: Historical Search

### ISSUE THREAD

**Issue by mime-frame** [airbnb/streamalert#5]
Target: Q3/Q4'17

For historical searching, StreamAlert will use AWS Athena, a serverless, interactive query service that uses Presto to query data in S3. This will allow you to analyze data using SQL for both ad-hoc and scheduled queries.

**Comment by elvarb** [comment]
Any plans to include elasticsearch support?

**Comment by mime-frame** [comment]
@elvarb - Nope, see https://streamalert.readthedocs.io/alternatives.html

**Comment by jacknagz** [comment]
To do:

Part 1:
- [ ] Configure Lambda to send directly to a datatype specific Firehose
- [ ] Append UUID's to all incoming records for alert references

Part 2:
- [ ] Reorganize all alerts into one single bucket
- [ ] Flatten the alert structure, add a key for the record uuid and table reference
- [ ] Update the s3 output to send this new flattened alert structure

Part 3:
- [ ] Create Athena tables from StreamAlert Schemas via the CLI
- [ ] Use Athena as an output option for Alerts (create a mapping for named queries)

**Comment by elvarb** [comment]
For others looking into Streamalert with Elasticsearch you could possibly do it like this for full on premise solution
* Streamalert -> Minio ( https://github.com/minio/minio-go ) 
* Minio -> Logstash ( https://www.elastic.co/guide/en/logstash/current/plugins-inputs-s3.html ) 
* Logstash -> Elasticsearch

**Comment by jacknagz** [comment]
[Interesting article](https://forums.aws.amazon.com/thread.jspa?threadID=244663) on the current drawbacks of Firehose and Athena

**Comment by jacknagz** [comment]
We might also be able to use [fastparquet](https://github.com/dask/fastparquet) for better searching performance
